### PR TITLE
fix(with-framer): update factory example and details

### LINKED ISSUE #541: Forward children when using chakra factory with framer-motion
### Subject

Chakra UI + Framer Motion

### Description

It seems that `isValidMotionProp` does not take `children` into account. Since a motionized `Box` is used in the example, it would be  fitting to also add the `children` in the  `shouldForwardProp` function or add a notice for this.

### PR DESCRIPTION
**Pull request by TylerAPfledderer**
Closes #541

## 📝 Description

This is an update to the Chakra Factory example for [Chakra + Framer](https://chakra-ui.com/guides/integrations/with-framer#usage), where it shows the inclusion of the `children` prop in `shouldForwardProps`

## ⛳️ Current behavior (updates)

Currently, `shouldForwardProp` only passes in `isValidMotionProp` so that the Framer animations are active and not overridden by matching props from Chakra. However, you can't use child components because the `children` props ends up being ignored, despite all other chakra props still available for use. This is not notated for users to be aware of.

## 🚀 New behavior

The inclusion of forwarding the `children` prop in `shouldForwardProps` is provided in the example with a comment underneath. All other chakra props not matching the motion props can still be used.

The overall example is updated to reflect the `children` prop being included.

### CODE REVIEW

File: configs/sandpack-contents/framer-motion-examples/chakra-factory.js [hunk 1]
```diff
@@ -1,47 +1,51 @@
...
-  </ChakraProvider>,
-  rootElement
-);`,
-}
+module.exports = {
+  App: `import { Container, chakra } from '@chakra-ui/react';
+  import { motion, isValidMotionProp } from 'framer-motion';
+    
+  const ChakraBox = chakra(motion.div, {
+    shouldForwardProp: (prop) => isValidMotionProp(prop) || prop === 'children',
```
Comment (noobinthisgame) [inline configs/sandpack-contents/framer-motion-examples/chakra-factory.js:6]: I would add a comment above here to make this bit point out more. Would make it easier to find after reading the hint bellow

**Review by noobinthisgame — CHANGES_REQUESTED** [review]
This is looking good already. I've left one little thought.

File: configs/sandpack-contents/framer-motion-examples/chakra-factory.js (hunk 1 above)
Comment (TylerAPfledderer) [reply configs/sandpack-contents/framer-motion-examples/chakra-factory.js:10]: Done!

**Comment by TylerAPfledderer** [comment]
@noobinthisgame PR has been updated! 😸

**Comment by noobinthisgame** [comment]
Great !

**Review by noobinthisgame — APPROVED** [review]
Let's go !
