### PR TITLE
Fix/double sponsor entries

### LINKED ISSUE #330: Double entries of organisation and individual sponsors on landing page
### Description

On the landing page are multiple entries doubled on the organization and individual sponsors section, see my screenshot below. After a bit of investigation I found out that in the [.all-sponsorsrc](https://github.com/chakra-ui/chakra-ui-docs/blob/main/.all-sponsorsrc) are people/organizations doubled with different `MemberIds`, e.g.:
Organizations:
- Shogun: 167894 and 189810
- Touchless: 98173 and 98175

Individuals:
- Segun Adebayo: 51659 and 179387
- Tim Kolberger: 158176 and 175726
- Javier Alaves: 219561 and 224250

Also organization without a website which are on the landing page (a tag without href):
- Chakra UI Pro -> obviously: https://pro.chakra-ui.com
- Touchless -> https://www.touchless.inc/

I'm not sure if it is enough to wipe out that doubled entries and add missing website-URLs in the file or there are other things to do. If this solves the problem once and for all just give me a 'go' or assign me then I will clean it up, 'hard work' is already done by creating this ticket.

Screenshot from 2022-02-16 22-04-52

### PR DESCRIPTION
**Pull request by m4x3d**
Closes #330 

## 📝 Description

Adds a filter for fetched sponsors from opencollective by the opencollective profile link to avoid double entries at the sponsors section. Also makes the link props on the organization sponsors conditional by the presence of the website link.

## ⛳️ Current behavior (updates)

- double entries on the sponsors section on the landingpage (see the screenshot in the issue)
- a tag without href for some organization sponsors without given website informations

## 🚀 New behavior

- sponsors are filtered now by the opencollective profile link
- conditional link props for organization sponsors depending on the website link

## 💣 Is this a breaking change (Yes/No):

No

### CODE REVIEW

File: scripts/avatars.ts [hunk 1]
```diff
@@ -18,12 +18,19 @@ async function getSponsors() {
...
+      s.profile === value.profile
+    ))
+  )
+  
   const individuals = sponsors.filter(
-    (i: any) => i.type === 'USER' && i.image != null,
+    (sponsor: any) => sponsor.type === 'USER' && sponsor.image != null,
   )
-  const companies = sponsors.filter((i: any) => i.type === 'ORGANIZATION')
+  const companies = sponsors.filter((sponsor: any) => sponsor.type === 'ORGANIZATION')
```
Comment (noobinthisgame) [inline scripts/avatars.ts:33]: Let's try to have all those anys typed properly :)

**Review by noobinthisgame — CHANGES_REQUESTED** [review]

**Review by nikolovlazar — APPROVED** [review]
LGTM! Just resolve the conflicts and it'll be ready to merge.

**Comment by m4x3d** [comment]
@nikolovlazar 
I just rebased the main branch. Probably it will have conflicts after the daily update PR again so I will check it tomorrow morning again.
