### PR TITLE
fix(component-links): allow overflow of the container

### LINKED ISSUE #619: Focus Outline from `ComponentLink` clipped
### Description

In any component doc page containing the github/npm links to view source, theme, etc., on focus of the link the outline shadow is getting cropped off. This is due to the combination of the negative margin and `overflow: hidden` rendered by the `Wrap` component user used in the [`ComponentLinks` component](https://github.com/chakra-ui/chakra-ui-docs/blob/main/src/components/mdx-components/component-links.tsx).

The simplest and cleanest solution is to apply `overflow: visible` to the `Wrap` component used.

Side note: The hover states of each link are also impacted. Because the link shifts on hover, you can visibly see the border being clipped by the hidden overflow.

### Screenshot
image

### PR DESCRIPTION
**Pull request by TylerAPfledderer**
Closes #619

Revert the `overflow` prop originally set from the `Wrap` component that contains the component links (i.e. source code, theme, npm) to allow the boxShadow on focus and the transition on hover to not be clipped.

Clipping comes from the combination of `overflow: hidden` and negative margins, both set by the `Wrap` component.

### CODE REVIEW

File: src/components/mdx-components/component-links.tsx [hunk 1]
```diff
@@ -1,144 +1,150 @@
...
+      spacing='4'
+      overflow='unset'
+      {...rest}
+    >
+      {githubLink}
+      {themeComponentLink}
+      {npmLink}
+      {storybookLink}
+      {videoLink}
+    </Wrap>
```
Comment (noobinthisgame) [inline src/components/mdx-components/component-links.tsx:146]: Could we replace this with a `ButtonGroup` and modify the `ComponentLink` to be a Button styled accordingly as Link ? I think that would clean up here this component a lot and be more chakra like

**Review by noobinthisgame — CHANGES_REQUESTED** [review]
Nice catch @TylerAPfledderer. I've left some thoughts.

File: src/components/mdx-components/component-links.tsx (hunk 1 above)
Comment (TylerAPfledderer) [reply src/components/mdx-components/component-links.tsx:146]: Ahh, yes! I'm on it! 🚀

Comment (TylerAPfledderer) [reply src/components/mdx-components/component-links.tsx:146]: @noobinthisgame I guess while I'm in here, do we still use the `ComponentLink`'s for Youtube and Storybook links? I've never seen them used in any of the docs.

Comment (noobinthisgame) [reply src/components/mdx-components/component-links.tsx]: Let's keep them for now, but add a comment above that they are unused if that's really the case.

**Comment by TylerAPfledderer** [comment]
@noobinthisgame good to check again!

File: src/components/mdx-components/component-links.tsx [hunk 2]
```diff
@@ -1,144 +1,145 @@
...
+      _hover={{
+        color: useColorModeValue('gray.700', 'whiteAlpha.900'),
+        bg: useColorModeValue('gray.300', 'whiteAlpha.300'),
+        boxShadow: 'sm',
+        transform: 'translateY(-1px)',
+        textDecor: 'none',
+      }}
+      {...rest}
+    >
+      <HStack>
```
Comment (noobinthisgame) [inline src/components/mdx-components/component-links.tsx:46]: You can use the leftIcon prop of the Button component to place the icons.

File: src/components/mdx-components/component-links.tsx [hunk 3]
```diff
@@ -1,144 +1,145 @@
...
+      icon={FaGithub}
+      iconColor={iconColor}
+      iconSize='1rem'
+    >
+      {t('component.mdx-components.component-links.view-theme-source')}
+    </ComponentLink>
+  )
+
+  return (
+    <ButtonGroup
```
Comment (noobinthisgame) [inline src/components/mdx-components/component-links.tsx:129]: Here we have a little responsiveness issue when on phone.

File: src/components/mdx-components/component-links.tsx [hunk 4]
```diff
@@ -1,144 +1,145 @@
...
+  icon: React.ElementType
+  url: string
+  iconSize?: string
+  iconColor?: string
+}
+
+function ComponentLink(props: ComponentLinkProps) {
+  const { icon, url, children, iconSize, iconColor, ...rest } = props
+  return (
+    <Button
```
Comment (noobinthisgame) [inline src/components/mdx-components/component-links.tsx:26]: It would be nice if the buttons could match the old design ? What do you think?

**Review by noobinthisgame — CHANGES_REQUESTED** [review]
I've left some thoughts :)

File: src/components/mdx-components/component-links.tsx (hunk 2 above)
Comment (TylerAPfledderer) [reply src/components/mdx-components/component-links.tsx:46]: With the Button component setup, have to use the `sx` prop to ensure the `iconSize` and `iconColor` passed in are used. No major issue there.

File: src/components/mdx-components/component-links.tsx (hunk 4 above)
Comment (TylerAPfledderer) [reply src/components/mdx-components/component-links.tsx:26]: Sure! I personally favor retaining the touch space the `Button` provides for the mobile accessibility. There is a compromise here. 😄 
image

Comment (noobinthisgame) [reply src/components/mdx-components/component-links.tsx:26]: A compromise is what I meant. Was just missing the border and backgroundcolor when I checked :)

**Comment by TylerAPfledderer** [comment]
@noobinthisgame alright, one more time! 😆

**Review by noobinthisgame — COMMENTED** [review]
Good job ! :)

**Review by noobinthisgame — APPROVED** [review]
